routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if(auth()->check()){
        $user = auth()->user();
        if ($user->hasRole('admin')) {
            return redirect()->route('admin.dashboard.index');
        }
        Auth::logout();

        return redirect()->route('login')->with([
            'flash_status' => 'error',
            'flash_message' => 'You are Unauthorized for this login.'
        ]);
    }
    return view('auth.login');
})->name('index');


Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);

        Route::resource('/customers', 'Backend\CustomerController');
        Route::resource('/users', 'Backend\UserController');
        Route::resource('/promotions', 'Backend\PromotionController');
        Route::resource('/orders', 'Backend\OrderController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');
        Route::resource('/category', 'Backend\CategoryController');
        Route::resource('/sliders', 'Backend\SliderController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);


        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });


});


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('update/promotion-status', 'Backend\AjaxController@updatePromotionStatus')->name('update.promotion-status');
    Route::get('update/promotion-is-featured', 'Backend\AjaxController@updatePromotionIsFeatured')->name('update.promotion-is-featured');
    Route::get('update/customer-subscription-status', 'Backend\AjaxController@updateCustomerSubscriptionStatus')->name('update.customer-subscription-status');


});

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;
use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('backend.aboutus.create', compact('aboutus'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'summary' => 'required',
            'description' => 'required',
        ], [
            'summary.required' => 'Summary is required.',
            'description.required' => 'Description is required.'
        ]);
        $aboutus = Aboutus::findOrFail(1);

        $aboutus->update([
            'summary' => $request->summary,
            'description' => $request->description
        ]);
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'About us description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\Promotion;
use App\Models\User;
use Illuminate\Http\Request;
use Session;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{

    public function updatePromotionStatus(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'promotion_status' => 'required'
        ], [
            'promotion_status.required' => "Order ID is Required.",
        ]);

        if (!$validator->fails()) {
            $promotion = Promotion::where('id', $request->get('id'))->first();
            $promotion->status = $request->get('promotion_status');
            $promotion->save();


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }

    public function updatePromotionIsFeatured(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'is_featured' => 'required'
        ], [
            'is_featured.required' => "Order ID is Required.",
        ]);

        if (!$validator->fails()) {
            $promotion = Promotion::where('id', $request->get('id'))->first();
            $promotion->is_featured = $request->is_featured === '1' ? true : false;
            $promotion->save();


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }

    public function updateCustomerSubscriptionStatus(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'subscription_status' => 'required'
        ], [
            'subscription_status.required' => "Subscription Status is Required.",
        ]);

        if (!$validator->fails()) {
            $customer = User::where('id', $request->get('id'))->first();
            $customer->subscription_status = $request->get('subscription_status');
            $customer->save();


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }


}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Service;
use App\Models\Category;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic as Image;


class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $service_categories = Category::orderBy('id', 'DESC')->get();
        return view('backend.service_category.index', compact('service_categories'));
    }

    public function create()
    {
        return view('backend.service_category.create');

    }

    public function show($id)
    {

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'thumbnail_image'                 => 'required|mimes:jpg,jpeg,png|max:2048',
            'slug' => 'required|unique:service_categories,slug',
            'description' => 'required',
        ], [
            'thumbnail_image.required' => 'Image  is required.',
        ]);


        if ($request->has('thumbnail_image')) {
            $image_new = $request->file('thumbnail_image');
            $name_new = $image_new->getClientOriginalName();
            $destinationPathThumbail = public_path('/uploads/service_category/thumbnails');
            $imagePathNre = $destinationPathThumbail . "/" . $name_new;

            $name_with_time = time() . '_' . $name_new;
            $image_new->move($destinationPathThumbail, $name_with_time);
            $thumbnail_image = $name_with_time;

        } else {
            $thumbnail_image = null;
        }

        Category::create([
            'name' => $request->name,
            'slug' => $request->slug,
            'thumbnail_image' => $thumbnail_image,
            'description' => $request->description,
            'is_available' => $request->is_available == '1' ? true : false
        ]);
        return redirect()->route('admin.category.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Category created successfully.'
            ]);

    }

    public function edit($id)
    {
        $service_category = Category::find($id);
        return view('backend.service_category.edit', compact('service_category'));
    }

    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'thumbnail_image' => 'mimes:png,jpg,jpeg',
            'description' => 'required',

        ], [
            'thumbnail_image.required' => 'Image  is required.',
        ]);

        $category = Category::find($id);


        if ($request->has('thumbnail_image')) {

            $image_new = $request->file('thumbnail_image');
            $name_new = $image_new->getClientOriginalName();
            $destinationPathThumbail = public_path('/uploads/service_category/thumbnails');
            $imagePathNre = $destinationPathThumbail . "/" . $name_new;

            $name_with_time = time() . '_' . $name_new;
            $image_new->move($destinationPathThumbail, $name_with_time);
            $thumbnail_image = $name_with_time;

        } else {
            $thumbnail_image = $category->thumbnail_image;;
        }
        $category->update([
            'name' => $request->name,
            'slug' => $request->slug,
            'thumbnail_image' => $thumbnail_image,
            'description' => $request->description,
            'is_available' => $request->is_available == '1' ? true : false
        ]);

        return redirect()->route('admin.category.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Category updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $service_category = Category::findOrFail($id);
        $service_category->delete();

        return redirect()->route('admin.category.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Category has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\OrderHistory;
use App\Models\Promotion;
use App\Models\User;
use Illuminate\Http\Request;
use DB;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index(Request $request)
    {
        $total_orders = OrderHistory::count();
        $vendor_counts = User::where('user_type', 'vendor')->count();
        $customer_counts = User::where('user_type', 'customer')->count();
        $promotions = Promotion::count();
        $currentYearSale = OrderHistory::whereDate('created_at','>=', date('Y'))->sum('grand_total');
        $previousYearSale = OrderHistory::whereDate('created_at','>=', date('Y',strtotime("-1 year")))->whereDate('created_at','<=', date('Y'))->sum('grand_total');
        return view('backend.dashboard.index', compact('vendor_counts', 'total_orders', 'customer_counts', 'promotions', 'currentYearSale', 'previousYearSale'));
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Resources\PromotionResource;
use App\Models\OrderHistory;
use App\Models\Promotion;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;


class OrderController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index(Request $request)
    {
        $orders = OrderHistory::whereVendorId($request->id)->with('customer')->get();
        return view('backend.orders.index', compact('orders'));
    }

    public function show($id)
    {

    }

    public function create(Request $request)
    {


    }

    public function listing()
    {
    }

    public function findById($id)
    {
    }

    public function update(Request $request, $id)
    {
    }

    public function destroy($id)
    {
    }


}

app/Http/Controllers/Backend/PrivacyController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\PrivacyPolicy;
use Illuminate\Http\Request;

class PrivacyController extends Controller
{
    public function index()
    {
        $privacyPolicy = PrivacyPolicy::first();
        return view('backend.privacypolicy.create', compact('privacyPolicy'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'description' => 'required',
        ], [
            'description.required' => 'Description is required.'
        ]);
        $privacyPolicy = PrivacyPolicy::findOrFail(1);

        $privacyPolicy->update([
            'description' => $request->description
        ]);
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'Privacy Policy description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $settings = Setting::orderBy('id', 'DESC')->get();
        return view('backend.settings.index', compact('settings'));
    }

    public function edit($id)
    {
        $setting = Setting::find($id);
        return view('backend.settings.edit', compact('setting'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'value' => 'required',
        ]);
        Setting::find($id)->update([
            'value' => $request->value,
        ]);
        return redirect()->route('admin.settings.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Setting updated successfully.'
            ]);

    }
}

resources/views/backend/service_category/create.blade.php
@extends('backend.layouts.master')
@section('title','Categories')
@section('content')

    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="card">
            <h5 class="card-header float-end"> Add {{ __('Category') }}</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.category.store') }}"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first  mb-3">


                                    <div class="form-group row">


                                        <div class="col-md-4">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Name') }}
                                                <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{{ old('name') }}"
                                                   autocomplete="name" autofocus>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-4">
                                            <label for="slug"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Slug') }}
                                                <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="slug" type="text"
                                                   class="form-control @error('slug') is-invalid @enderror"
                                                   name="slug" value="{{ old('slug') }}"
                                                   autocomplete="slug" autofocus>

                                            @error('slug')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-4">
                                            <label for="inputGroupSelect02"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Status') }}</label>

                                            <select id="inputGroupSelect02"
                                                    class="form-select @error('is_available') is-invalid @enderror"
                                                    name="is_available" autocomplete="is_available">
                                                <option value="0">In-active</option>
                                                <option value="1" selected>Active</option>
                                            </select>
                                            @error('is_available')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>


                                    <div class="form-group row">

                                        <div class="col-md-12">
                                            <label for="description"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Description') }}
                                                <span class="mandatorySign">*</span></label>

                                            <textarea id="description"
                                                      class="form-control @error('description') is-invalid @enderror"
                                                      name="description" rows="5" cols="15"
                                                      autocomplete="description"></textarea>

                                            @error('description')
                                            <span class="invalid-feedback" role="alert">
                                              <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>


                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-6">
                                            <label for="thumbnail_image" id="image_thumb"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Image') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input value="{{old('thumbnail_image')}}" type="file"
                                                   id="thumbnail_image"
                                                   class="form-control @error('thumbnail_image') is-invalid @enderror"
                                                   onchange="readURLThumbnail(this)"
                                                   name="thumbnail_image" style="padding: 9px; cursor: pointer">
                                            <img width="300" height="200" class="img-thumbnail"
                                                 style="display:none;"
                                                 id="img_thumbnail" src="#"
                                                 alt="your image"/>

                                            @error('image')
                                            <span class="invalid-feedback" role="alert">
                                              <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>


                                </div>

                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right float-end">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.category.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>

        </div>

    </div>
@endsection


@push('js')
@endpush


@push('js')
    <script>
        $('#name').focusout(function () {

            var name = $(this).val();
            name = name.replace(/\s+/g, '-').toLowerCase();

            $('#slug').val(name);
        })
    </script>
@endpush

resources/views/backend/service_category/index.blade.php
@extends('backend.layouts.master')
@section('title','Categories')
@push('css')
    <style>
        #m_table_1_wrapper {
            margin: 20px !important;
        }
    </style>
@endpush
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="card">
            <h5 class="card-header float-end">
                <a href="{{ route('admin.category.create') }}"
                   class="btn btn-primary float-end">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Category</span>
                                </span>
                </a></h5>
            <div class="table-responsive text-nowrap">
                <table class="table" id="m_table_1">
                    <thead>
                    <tr class="text-nowrap">

                        <th> Sr NO.</th>
                        <th> Name</th>
                        <th> Status</th>
                        <th> Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($service_categories))
                        @foreach($service_categories as $service_category)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$service_category->name}}</td>
                                @if($service_category->is_available == 1)

                                    <td><span class="badge bg-label-primary me-1">Active</span></td>
                                @else
                                    <td><span class="badge bg-label-warning me-1">In-active</span></td>
                                @endif

                                <td>
                                    <div class="dropdown">
                                        <button type="button" class="btn p-0 dropdown-toggle hide-arrow"
                                                data-bs-toggle="dropdown">
                                            <i class="bx bx-dots-vertical-rounded"></i>
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="{{route('admin.category.edit',$service_category->id)}}"
                                               class="dropdown-item"><i class="bx bx-edit-alt me-1"></i> Edit</a>
                                            <form method="post"
                                                  action="{{ route('admin.category.destroy', $service_category->id) }}"
                                                  id="delete_{{ $service_category->id }}">
                                                @csrf
                                                @method('DELETE')
                                                <a class="dropdown-item"
                                                   href="javascript:void(0)"
                                                   onclick="if(confirmDelete()){ document.getElementById('delete_<?=$service_category->id?>').submit(); }">
                                                    <i class="bx bx-trash me-1"></i> Delete
                                                </a>
                                            </form>

                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "columnDefs": [
                {orderable: false, targets: [2]}
            ],
        });
    </script>
@endpush