routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if(auth()->check()){
        $user = auth()->user();
        if ($user->hasRole('admin')) {
            return redirect()->route('admin.dashboard.index');
        }
        Auth::logout();

        return redirect()->route('login')->with([
            'flash_status' => 'error',
            'flash_message' => 'You are Unauthorized for this login.'
        ]);
    }
    return view('auth.login');
})->name('index');


Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);

        Route::resource('/customers', 'Backend\CustomerController');
        Route::resource('/users', 'Backend\UserController');
        Route::resource('/promotions', 'Backend\PromotionController');
        Route::resource('/orders', 'Backend\OrderController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');
        Route::resource('/category', 'Backend\CategoryController');
        Route::resource('/sliders', 'Backend\SliderController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);


        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


    });


});


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('update/promotion-status', 'Backend\AjaxController@updatePromotionStatus')->name('update.promotion-status');
    Route::get('update/promotion-is-featured', 'Backend\AjaxController@updatePromotionIsFeatured')->name('update.promotion-is-featured');
    Route::get('update/customer-subscription-status', 'Backend\AjaxController@updateCustomerSubscriptionStatus')->name('update.customer-subscription-status');


});

resources/views/frontend/include/footer.blade.php
@php
    $settings =\App\Models\Setting::all();
@endphp

<footer>
    <div class="container">
        <div class="col-md-4 col-sm-4 col-xs-6">
            <img src="{{ asset('frontend/images/footerLogo.png') }}" alt="">
            <div class="row">
                <div class="col-md-12">
                    <ul class="list-unstyled">
                        <li><a href="mailto:{{$settings[1]->value}}"><i
                                    class="fa fa-envelope"></i> {{$settings[1]->value}}</a></li>
                        <li><a href="tel:{{$settings[0]->value}}"><i class="fa fa-phone"></i> {{$settings[0]->value}}
                            </a></li>
                    </ul>
                    <ul class="list-unstyled list-inline">
                        <li><a href="{{$settings[8]->value}}" target="_blank"><i class="fab fa-whatsapp"></i></a></li>
                        <li><a href="{{$settings[9]->value}}" target="_blank"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="{{$settings[10]->value}}" target="_blank"><i class="fab fa-facebook"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-6 quickLinks">
            <h3>Quick Links</h3>
            <ul class="list-unstyled">
                <li><a href="{{ route('aboutus.detail') }}">About</a></li>
                <li><a href="{{ route('service') }}">Services</a></li>
                <li><a href="{{ route('blog') }}">Special Offers</a></li>
                <li><a href="{{ route('contacts.create') }}">Contact</a></li>

                @if(auth()->check() && auth()->user()->user_type  == 'customer')
                    <li><a href="{{ route('service') }}">Packages</a></li>
                @else
                    <li><a href="{{ route('packages') }}">Packages</a></li>
                @endif
                <li><a href="{{ route('privacy.policy') }}">Privacy Policy</a></li>

            </ul>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-6 footerLastArea">
            <div class="col-md-4 col-sm-4 col-xs-4">
                <img src="{{ asset('frontend/images/footerMob.png') }}" alt="">
            </div>
            <div class="col-md-8 col-sm-8 col-xs-8 footerLastAreaImages">
                <h3>Saver Buddy</h3>
{{--                <h4>Download App Now</h4>--}}
                <h4>App Coming Soon</h4>
                <a href="#"><img src="{{ asset('frontend/images/appStore.png') }}" alt="AppStore"></a>
                <a href="#"><img src="{{ asset('frontend/images/googlePlay.png') }}" alt="GooglePlay"></a>
            </div>
        </div>
    </div>
</footer>

resources/views/frontend/include/header.blade.php
<div class="topbar">
    <div class="container">
        <div class="row">
            <div class="responsiveLogo">
                <a href="{{ route('login') }}"><img src="{{ asset('frontend/images/logo.png') }}" alt=""></a>
            </div>

        </div>
    </div>
</div>

resources/views/frontend/include/meta-tags.blade.php
@if(Route::currentRouteName() == 'service.items' || Route::currentRouteName() == 'category.blogs' ||  Route::currentRouteName() == 'package.show' || Route::currentRouteName() == 'blog.show')
    <title>Saver Buddy | @yield('title')</title>
    <meta name="description" content="@yield('description')">
    <meta name="keywords" content="@yield('keywords')">
@elseif(is_null($meta_information))
    <title>Saver Buddy | @yield('title')</title>
    <meta name="description"
          content="Find The Best Discount Deals In Ghana Daily!">
    <meta name="keywords" content="Saver Buddy">
@else
    <title>Saver Buddy | {{$meta_information->title}}</title>
    <meta name="description" content="{{ $meta_information->description }}">
    <meta name="keywords" content="{{ $meta_information->keywords }}">
@endif

<meta name="msapplication-TileImage" content="https://saverbuddy.app/wp-content/uploads/2023/03/cropped-SAVERBUDDY-LOGO_221208_140636-270x270.png">

resources/views/frontend/include/navbar.blade.php
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header customLogo">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#defaultNavbar1">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span></button>
            <a class="navbar-brand" href="{{ route('index') }}"><img src="{{ asset('frontend/images/logo.png') }}"
                                                                     alt=""></a></div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="defaultNavbar1">
            <ul class="nav navbar-nav">

                <li class="{{ (request()->is('/')) ? 'active' : '' }}"><a href="{{ route('index') }}">Home
                    </a>
                </li>
                @guest
                    <li class="hidden-lg hidden-md hidden-sm"><a href="{{ route('login') }}"
                                                       class=" {{ (request()->is('login')) ? 'active' : '' }}">Login</a>
                    </li>
                    <li class="hidden-lg hidden-md hidden-sm"><a href="{{ route('register') }}"
                                                       class="{{ (request()->is('register')) ? 'active' : '' }}">Register</a>
                    </li>
                @endguest
                @if(auth()->check() && auth()->user()->user_type  == 'customer')
                    <li class="{{ (request()->is('services')) ? 'active' : '' }} hidden-xs"><a href="{{ route('service') }}">Services
                            & Packages</a></li>
                    <li class="{{ (request()->is('services')) ? 'active' : '' }} hidden-lg hidden-md hidden-sm"><a href="{{ route('service') }}" >Packages</a>
                    </li>
                    <li class="{{ (request()->is('services')) ? 'active' : '' }} hidden-lg hidden-md hidden-sm"><a href="{{ route('service') }}">Services</a></li>



                @else
                    <li class="{{ (request()->is('services')) ? 'active' : '' }}"><a href="{{ route('service') }}">Services</a>
                    </li>
                @endif






                @if(auth()->check() && auth()->user()->user_type  == 'customer')
                    <li class="{{ (request()->is('customer/referrals')) ? 'active' : '' }}"><a
                            href="{{ route('customer.user.referral') }}">Refer a Friend</a></li>
                @else
                    <li class="{{ (request()->is('packages')  || request()->is('packages/*')) ? 'active' : '' }}"><a href="{{ route('packages') }}">Packages</a>
                    </li>
                @endif

            </ul>

            <ul class="nav navbar-nav navbar-right">

                <li class="{{ (request()->is('about-us')) ? 'active' : '' }}"><a href="{{ route('aboutus.detail') }}">About
                        Us</a>
                </li>
                @auth

                @if(auth()->user()->hasRole('admin'))
                    <li class="hidden-lg hidden-md hidden-sm">
                        <a href="{{ route('admin.dashboard.index') }}"
                           class="profileImage {{ (request()->is('about-us')) ? 'active' : '' }}"
                           title="{{ auth()->user()->fullName() }}">Dashboard
                        </a>
                    </li>
                @elseif(auth()->user()->hasRole('customer'))
                    <li class="hidden-lg hidden-md hidden-sm">
                        <a href="{{ route('customer.order.history') }}"
                           class="profileImage {{ (request()->is('customer/order-history')) ? 'active' : '' }}"
                           title="Orders">Orders
                        </a>
                    </li>
                    <li class="hidden-lg hidden-md hidden-sm">
                        <a href="{{ route('customer.profile.index') }}"
                           class="profileImage {{ (request()->is('customer/profile/*')) ? 'active' : '' }}"
                           title="Profile">Profile
                        </a>
                    </li>


                @endif
                @endauth

                {{--                <li class="{{ (request()->is('blogs')) ? 'active' : '' }}"><a href="{{ route('blog') }}">Blog</a></li>--}}
                <li class="{{ (request()->is('memberships')) ? 'active' : '' }}"><a href="{{ route('memberships') }}">Membership</a>
                </li>
                <li class="{{ (request()->is('contacts')) ? 'active' : '' }} hidden-xs"><a href="{{ route('contacts.create') }}">Contact</a>
                </li>
                @auth
                <li class="hidden-lg hidden-md hidden-sm">
                    <a href="{{ route('logout') }}" class="btn buttonMain hvr-bounce-to-right"
                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                </li>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
                @endauth

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

resources/views/frontend/include/rating.blade.php
<script>

    $('#orderRating').modal('show');
    $('#orderRating').css('display', 'block');

    // 1. Visualizing things on Hover - See next part for action on click
    $('#stars li').on('mouseover', function () {
        var onStar = parseInt($(this).data('value'), 10); // The star currently mouse on

        // Now highlight all the stars that's not after the current hovered star
        $(this).parent().children('li.star').each(function (e) {
            if (e < onStar) {
                $(this).addClass('hover');
            } else {
                $(this).removeClass('hover');
            }
        });

    }).on('mouseout', function () {
        $(this).parent().children('li.star').each(function (e) {
            $(this).removeClass('hover');
        });
    });


    // 2. Action to perform on click

    $('#stars li').on('click', function () {
        var onStar = parseInt($(this).data('value'), 10); // The star currently selected
        var stars = $(this).parent().children('li.star');

        for (i = 0; i < stars.length; i++) {
            $(stars[i]).removeClass('selected');
        }

        for (i = 0; i < onStar; i++) {
            $(stars[i]).addClass('selected');
        }

        // JUST RESPONSE (Not needed)
        var ratingValue = parseInt($('#stars li.selected').last().data('value'), 10);
        var selectedRating = $('#stars li.selected').last().data('type');

        if (selectedRating === 'time') {
            $('#rate_star_1').val(ratingValue);
        } else if (selectedRating === 'profession') {
            $('#rate_star_2').val(ratingValue);
        } else {
            $('#rate_star_3').val(ratingValue);
        }


        if ((parseInt($('#rate_star_1').val()) > 1) && (parseInt($('#rate_star_2').val()) > 1) && (parseInt($('#rate_star_3').val()) > 1)) {
            $('#disable-btn').removeAttr('disabled');
        }

    });

    function submitRatingForm(){

        let form    = $("#rating-form-in-modal");
        var request = $(form).serialize();

        $.ajax({
            type: "POST",
            url: "{{ route('ajax.order.staff.rating') }}",
            data: request,
            dataType: "json",
            cache: true,
            success: function (response) {
                if (response.status == "success") {

                    toastr['success']("Thanks for Rating.We Will Improve ourselves.");
                    window.location.reload();
                }
            },
            error: function () {
                toastr['error']("Something Went Wrong.");
            }
        });
    }


</script>

resources/views/frontend/include/sticky.blade.php
<div class="copyright">
    <div class="container">
        <p>© copyright Saver Buddy {{ date('Y') }} </span></p>
    </div>
</div>